# Generated by Django 4.1.2 on 2022-10-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivos')),
            ],
        ),
        migrations.CreateModel(
            name='FileSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.ManyToManyField(null=True, related_name='self', to='file_system.filesystem')),
                ('files', models.ManyToManyField(to='file_system.files')),
            ],
        ),
    ]
