# Generated by Django 4.1.2 on 2022-10-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystem',
            name='directory',
            field=models.ManyToManyField(blank=True, null=True, related_name='self', to='file_system.filesystem'),
        ),
    ]
